// MsgVals.h 

//Menu bar messages
#define TIMEBOMB_SETTINGS        	B_SPECIFIERS_END+1

//Main window messages
#define TIMEBOMB_STOP_ALARM			B_SPECIFIERS_END+5

//Settings menu messages
#define TIMEBOMB_VOL_CHANGE			B_SPECIFIERS_END+10
#define TIMEBOMB_AUDIBLE_CHANGE 	B_SPECIFIERS_END+11
#define TIMEBOMB_HOUR_CHANGE   		B_SPECIFIERS_END+12
#define TIMEBOMB_MIN_CHANGE    		B_SPECIFIERS_END+13 
#define TIMEBOMB_AMPM_CHANGE   		B_SPECIFIERS_END+14
#define TIMEBOMB_HOUR_CHANGE_2   	B_SPECIFIERS_END+15
#define TIMEBOMB_MIN_CHANGE_2    	B_SPECIFIERS_END+16 
#define TIMEBOMB_AMPM_CHANGE_2   	B_SPECIFIERS_END+17
#define	TIMEBOMB_SOUND_CHANGE		B_SPECIFIERS_END+18
#define	TIMEBOMB_COLOR_CHANGE		B_SPECIFIERS_END+19
#define	TIMEBOMB_NUMRINGS_CHANGE	B_SPECIFIERS_END+20
#define TIMEBOMB_ALARM_MSG_CHANGE_1 B_SPECIFIERS_END+21
#define TIMEBOMB_ALARM_MSG_CHANGE_2 B_SPECIFIERS_END+22
#define TIMEBOMB_CD_CHANGE			B_SPECIFIERS_END+23
#define TIMEBOMB_CD_TRACK_CHANGE	B_SPECIFIERS_END+24
#define TIMEBOMB_WHOLE_SONG_CHANGE	B_SPECIFIERS_END+25
#define TIMEBOMB_CD_DEVICE_CHANGE	B_SPECIFIERS_END+26

#define TIMEBOMB_SETWIN_QUIT		B_SPECIFIERS_END+30

//Shutdown messages
#define TIMEBOMB_END				B_SPECIFIERS_END+31
#define TIMEBOMB_END_VARS			B_SPECIFIERS_END+32

